# Generated by Django 4.1.3 on 2022-11-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_emprendimiento', models.CharField(choices=[('hospedaje', 'Hospedaje'), ('restaurantes', 'Restaurante'), ('spots', 'Spot Turistico'), ('productores', 'Productor - Vendedor')], max_length=200, verbose_name='Tipo de Emprendimiento')),
                ('empresa', models.CharField(max_length=200, verbose_name='Nombre del Emprendimiento')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('decripcion', models.TextField()),
                ('horario_apertura', models.DateTimeField()),
                ('horario_cierre', models.DateTimeField()),
                ('altitud', models.CharField(max_length=20, verbose_name='Altitud')),
                ('latitud', models.CharField(max_length=20, verbose_name='Latitud')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_local', verbose_name='Logo')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video Promocional')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('num_documento', models.CharField(max_length=13, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefono', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=13, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pais_origen', models.CharField(max_length=200, verbose_name='País de origen')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField(max_length=4, verbose_name='Cantidad del Prodcuto')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('emprendimientos', models.ManyToManyField(blank=True, null=True, to='administracion.emprendimiento')),
            ],
            options={
                'verbose_name': 'Emprendedor',
                'verbose_name_plural': 'Emprendedores',
            },
            bases=('administracion.persona',),
        ),
    ]
